lovelace:
  mode: yaml
  dashboards:
    hotel-reception:
      mode: yaml
      title: Hotel Reception
      icon: mdi:hotel
      show_in_sidebar: true
      filename: dashboards/hotel-reception.yaml
